export const bestsellerdata = [
  {
    id: 1,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "30000MMK",
    description: "UI/UX designing, html css tutorials",
    content:
      "Welcome to our channel Dev AT. Here you can learn web designing, UI/UX designing, html css tutorials, css animations and css effects, javascript and jquery tutorials and related so on.",
    product_image: "./images/shampoo/S11.png",
    detail_image: [
      "../images/shampoo/S11.png",
      "../images/Lipstick/L21.png",
      "../images/Lipstick/L22.png",
      "../images/Lipstick/L23.png",
    ],
    colors: ["red", "black", "crimson", "teal"],
    count: 1,
  },
  {
    id: 2,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "280000MMK",
    description: "UI/UX designing, html css tutorials",
    content:
      "Welcome to our channel Dev AT. Here you can learn web designing, UI/UX designing, html css tutorials, css animations and css effects, javascript and jquery tutorials and related so on.",
    product_image: "./images/shampoo/S13.png",
    detail_image: [
      "../images/shampoo/S13.png",
      "../images/Lipstick/L21.png",
      "../images/Lipstick/L22.png",
      "../images/Lipstick/L23.png",
    ],
    colors: ["red", "black", "crimson", "teal"],
    count: 1,
  },
  {
    id: 3,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "240000MMK",
    description: "UI/UX designing, html css tutorials",
    content:
      "Welcome to our channel Dev AT. Here you can learn web designing, UI/UX designing, html css tutorials, css animations and css effects, javascript and jquery tutorials and related so on.",
    product_image: "./images/shampoo/S15.png",
    detail_image: [
      "../images/shampoo/S15.png",
      "../images/Lipstick/L21.png",
      "../images/Lipstick/L22.png",
      "../images/Lipstick/L23.png",
    ],
    colors: ["red", "black", "crimson", "teal"],
    count: 1,
  },
  {
    id: 4,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "330000MMK",
    description: "UI/UX designing, html css tutorials",
    content:
      "Welcome to our channel Dev AT. Here you can learn web designing, UI/UX designing, html css tutorials, css animations and css effects, javascript and jquery tutorials and related so on.",
    product_image: "./images/shampoo/S17.png",
    detail_image: [
      "../images/shampoo/S17.png",
      "../images/Lipstick/L21.png",
      "../images/Lipstick/L22.png",
      "../images/Lipstick/L23.png",
    ],
    colors: ["red", "black", "crimson", "teal"],
    count: 1,
  },
  {
    id: 5,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "190000MMK",
    description: "UI/UX designing, html css tutorials",
    content:
      "Welcome to our channel Dev AT. Here you can learn web designing, UI/UX designing, html css tutorials, css animations and css effects, javascript and jquery tutorials and related so on.",
    product_image: "./images/shampoo/S13.png",
    detail_image: [
      "../images/shampoo/S13.png",
      "../images/Lipstick/L21.png",
      "../images/Lipstick/L22.png",
      "../images/Lipstick/L23.png",
    ],
    colors: ["red", "black", "crimson", "teal"],
    count: 1,
  },
  {
    id: 6,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    description: "UI/UX designing, html css tutorials",
    content:
      "Welcome to our channel Dev AT. Here you can learn web designing, UI/UX designing, html css tutorials, css animations and css effects, javascript and jquery tutorials and related so on.",
    product_image: "./images/shampoo/S11.png",
    detail_image: [
      "../images/shampoo/S11.png",
      "../images/Lipstick/L21.png",
      "../images/Lipstick/L22.png",
      "../images/Lipstick/L23.png",
    ],
    colors: ["red", "black", "crimson", "teal"],
    count: 1,
  },
  {
    id: 7,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    description: "UI/UX designing, html css tutorials",
    content:
      "Welcome to our channel Dev AT. Here you can learn web designing, UI/UX designing, html css tutorials, css animations and css effects, javascript and jquery tutorials and related so on.",
    product_image: "./images/shampoo/S12.png",
    detail_image: [
      "../images/shampoo/S12.png",
      "../images/Lipstick/L21.png",
      "../images/Lipstick/L22.png",
      "../images/Lipstick/L23.png",
    ],
    colors: ["red", "black", "crimson", "teal"],
    count: 1,
  },
  {
    id: 8,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    description: "UI/UX designing, html css tutorials",
    content:
      "Welcome to our channel Dev AT. Here you can learn web designing, UI/UX designing, html css tutorials, css animations and css effects, javascript and jquery tutorials and related so on.",
    product_image: "./images/skin-care/S3.png",
    detail_image: [
      "../images/skin-care/S3.png",
      "../images/Lipstick/L21.png",
      "../images/Lipstick/L22.png",
      "../images/Lipstick/L23.png",
    ],
    colors: ["red", "black", "crimson", "teal"],
    count: 1,
  },
  {
    id: 9,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    description: "UI/UX designing, html css tutorials",
    content:
      "Welcome to our channel Dev AT. Here you can learn web designing, UI/UX designing, html css tutorials, css animations and css effects, javascript and jquery tutorials and related so on.",
    product_image: "./images/shampoo/S12.png",
    detail_image: [
      "../images/shampoo/S12.png",
      "../images/Lipstick/L21.png",
      "../images/Lipstick/L22.png",
      "../images/Lipstick/L23.png",
    ],
    colors: ["red", "black", "crimson", "teal"],
    count: 1,
  },
  {
    id: 10,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "170000MMK",
    description: "UI/UX designing, html css tutorials",
    content:
      "Welcome to our channel Dev AT. Here you can learn web designing, UI/UX designing, html css tutorials, css animations and css effects, javascript and jquery tutorials and related so on.",
    product_image: "./images/shampoo/S15.png",
    detail_image: [
      "../images/shampoo/S15.png",
      "../mages/Lipstick/L21.png",
      "../images/Lipstick/L22.png",
      "../images/Lipstick/L23.png",
    ],
    colors: ["red", "black", "crimson", "teal"],
    count: 1,
  },
  {
    id: 11,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "430000MMK",
    description: "UI/UX designing, html css tutorials",
    content:
      "Welcome to our channel Dev AT. Here you can learn web designing, UI/UX designing, html css tutorials, css animations and css effects, javascript and jquery tutorials and related so on.",
    product_image: "./images/skin-care/S11.png",
    detail_image: [
      "../images/skin-care/S11.png",
      "../images/Lipstick/L21.png",
      "../images/Lipstick/L22.png",
      "../images/Lipstick/L23.png",
    ],
    colors: ["red", "black", "crimson", "teal"],
    count: 1,
  },
  {
    id: 12,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "53000MMK",
    description: "UI/UX designing, html css tutorials",
    content:
      "Welcome to our channel Dev AT. Here you can learn web designing, UI/UX designing, html css tutorials, css animations and css effects, javascript and jquery tutorials and related so on.",
    product_image: "./images/skin-care/S12.png",
    detail_image: [
      "../images/skin-care/S12.png",
      "../images/Lipstick/L21.png",
      "../images/Lipstick/L22.png",
      "../images/Lipstick/L23.png",
    ],
    colors: ["red", "black", "crimson", "teal"],
    count: 1,
  },
  {
    id: 13,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "230000MMK",
    description: "UI/UX designing, html css tutorials",
    content:
      "Welcome to our channel Dev AT. Here you can learn web designing, UI/UX designing, html css tutorials, css animations and css effects, javascript and jquery tutorials and related so on.",
    product_image: "./images/skin-care/S13.png",
    detail_image: [
      "../images/skin-care/S13.png",
      "../images/Lipstick/L21.png",
      "../images/Lipstick/L22.png",
      "../images/Lipstick/L23.png",
    ],
    colors: ["red", "black", "crimson", "teal"],
    count: 1,
  },
  {
    id: 14,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "120000MMK",
    description: "UI/UX designing, html css tutorials",
    content:
      "Welcome to our channel Dev AT. Here you can learn web designing, UI/UX designing, html css tutorials, css animations and css effects, javascript and jquery tutorials and related so on.",
    product_image: "./images/skin-care/S14.png",
    detail_image: [
      "../images/skin-care/S14.png",
      "../images/Lipstick/L21.png",
      "../images/Lipstick/L22.png",
      "../images/Lipstick/L23.png",
    ],
    colors: ["red", "black", "crimson", "teal"],
    count: 1,
  },
  {
    id: 15,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "110000MMK",
    description: "UI/UX designing, html css tutorials",
    content:
      "Welcome to our channel Dev AT. Here you can learn web designing, UI/UX designing, html css tutorials, css animations and css effects, javascript and jquery tutorials and related so on.",
    product_image: "./images/skin-care/S2.png",
    detail_image: [
      "../images/skin-care/S2.png",
      "../images/Lipstick/L21.png",
      "../images/Lipstick/L22.png",
      "../images/Lipstick/L23.png",
    ],
    colors: ["red", "black", "crimson", "teal"],
    count: 1,
  },
  {
    id: 16,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "70000MMK",
    description: "UI/UX designing, html css tutorials",
    content:
      "Welcome to our channel Dev AT. Here you can learn web designing, UI/UX designing, html css tutorials, css animations and css effects, javascript and jquery tutorials and related so on.",
    product_image: "./images/skin-care/S16.png",
    detail_image: [
      "../images/skin-care/S16.png",
      "../images/Lipstick/L21.png",
      "../images/Lipstick/L22.png",
      "../images/Lipstick/L23.png",
    ],
    colors: ["red", "black", "crimson", "teal"],
    count: 1,
  },
];
