export const skin_fraijour = {
  skincareData: [
    {
      id: 1,
      title: "Ordinary",
      name: "Fraijour Original Herb Wormwood Calming Toner",
      price: "130000MMK",
      image: "./images/skin-care/S21.png",
    },
    {
      id: 2,
      title: "Fraijour",
      name: "Fraijour Original Herb Wormwood Calming Toner",
      price: "180000MMK",
      image: "./images/skin-care/S2.png",
    },
    {
      id: 3,
      title: "Fraijour",
      name: "Fraijour Original Herb Wormwood Calming Toner",
      price: "240000MMK",
      image: "./images/skin-care/S3.png",
    },
    {
      id: 4,
      title: "Dr.G",
      name: "Fraijour Original Herb Wormwood Calming Toner",
      price: "330000MMK",
      image: "./images/skin-care/S4.png",
    },
    {
      id: 5,
      title: "Dr.G",
      name: "Fraijour Original Herb Wormwood Calming Toner",
      price: "190000MMK",
      image: "./images/skin-care/S5.png",
    },
    {
      id: 6,
      title: "Innisfree",
      name: "Fraijour Original Herb Wormwood Calming Toner",
      price: "130000MMK",
      image: "./images/skin-care/S7.png",
    },
    {
      id: 7,
      title: "Innisfree",
      name: "Fraijour Original Herb Wormwood Calming Toner",
      price: "130000MMK",
      image: "./images/skin-care/S8.png",
    },
    {
      id: 8,
      title: "Dr.G",
      name: "Fraijour Original Herb Wormwood Calming Toner",
      price: "130000MMK",
      image: "./images/skin-care/S6.png",
    },
    {
      id: 9,
      title: "Innisfree",
      name: "Fraijour Original Herb Wormwood Calming Toner",
      price: "130000MMK",
      image: "./images/skin-care/S9.png",
    },
    {
      id: 10,
      title: "Innisfree",
      name: "Fraijour Original Herb Wormwood Calming Toner",
      price: "170000MMK",
      image: "./images/skin-care/S10.png",
    },
    {
      id: 11,
      title: "Chanal",
      name: "Fraijour Original Herb Wormwood Calming Toner",
      price: "430000MMK",
      image: "./images/skin-care/S11.png",
    },
    {
      id: 12,
      title: "The Body Shop",
      name: "Fraijour Original Herb Wormwood Calming Toner",
      price: "53000MMK",
      image: "./images/skin-care/S12.png",
    },
    {
      id: 13,
      title: "The Body Shop",
      name: "Fraijour Original Herb Wormwood Calming Toner",
      price: "230000MMK",
      image: "./images/skin-care/S13.png",
    },
    {
      id: 14,
      title: "Some By Mi",
      name: "Fraijour Original Herb Wormwood Calming Toner",
      price: "120000MMK",
      image: "./images/skin-care/S14.png",
    },
    {
      id: 15,
      title: "Some By Mi",
      name: "Fraijour Original Herb Wormwood Calming Toner",
      price: "110000MMK",
      image: "./images/skin-care/S14.png",
    },
    {
      id: 16,
      title: "Some By Mi",
      name: "Fraijour Original Herb Wormwood Calming Toner",
      price: "70000MMK",
      image: "./images/skin-care/S16.png",
    },
  ],
};

export const skin_somebymi = [
  {
    id: 1,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/Makeup/mk12.png",
  },
  {
    id: 2,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "140000MMK",
    image: "./images/Makeup/mk13.png",
  },
  {
    id: 3,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "30000MMK",
    image: "./images/Makeup/mk12.png",
  },
  {
    id: 4,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "40000MMK",
    image: "./images/Makeup/mk3.png",
  },
  {
    id: 5,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "180000MMK",
    image: "./images/Makeup/mk6.png",
  },
  {
    id: 6,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "380000MMK",
    image: "./images/Makeup/mk8.png",
  },
  {
    id: 7,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "560000MMK",
    image: "./images/Makeup/mk10.png",
  },
  {
    id: 8,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "780000MMK",
    image: "./images/Makeup/mk8.png",
  },
  {
    id: 9,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/Makeup/mk11.png",
  },
  {
    id: 10,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/Makeup/mk12.png",
  },
  {
    id: 11,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/Makeup/mk17.png",
  },
  {
    id: 12,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "380000MMK",
    image: "./images/Makeup/mk8.png",
  },
  {
    id: 13,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "560000MMK",
    image: "./images/Makeup/mk10.png",
  },
  {
    id: 14,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "780000MMK",
    image: "./images/Makeup/mk8.png",
  },
  {
    id: 15,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/Makeup/mk11.png",
  },
  {
    id: 16,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/Makeup/mk12.png",
  },
];

export const skin_innifree = [
  {
    id: 1,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/Makeup/mk12.png",
  },
  {
    id: 2,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "140000MMK",
    image: "./images/Makeup/mk13.png",
  },
  {
    id: 3,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "30000MMK",
    image: "./images/Makeup/mk12.png",
  },
  {
    id: 4,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "40000MMK",
    image: "./images/Makeup/mk3.png",
  },
  {
    id: 5,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "180000MMK",
    image: "./images/Makeup/mk6.png",
  },
  {
    id: 6,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "380000MMK",
    image: "./images/Makeup/mk8.png",
  },
  {
    id: 7,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "560000MMK",
    image: "./images/Makeup/mk10.png",
  },
  {
    id: 8,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "780000MMK",
    image: "./images/Makeup/mk8.png",
  },
  {
    id: 9,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/Makeup/mk11.png",
  },
  {
    id: 10,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/Makeup/mk12.png",
  },
  {
    id: 11,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "50000MMK",
    image: "./images/Makeup/mk17.png",
  },
  {
    id: 12,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "380000MMK",
    image: "./images/Makeup/mk8.png",
  },
  {
    id: 13,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "560000MMK",
    image: "./images/Makeup/mk10.png",
  },
  {
    id: 14,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "780000MMK",
    image: "./images/Makeup/mk8.png",
  },
  {
    id: 15,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/Makeup/mk11.png",
  },
  {
    id: 16,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/Makeup/mk12.png",
  },
];

export const makeup_foundation = [
  {
    id: 1,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/skin-care/S21.png",
  },
  {
    id: 2,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "140000MMK",
    image: "./images/skin-care/S2.png",
  },
  {
    id: 3,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "30000MMK",
    image: "./images/Makeup/mk12.png",
  },
  {
    id: 4,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "40000MMK",
    image: "./images/Makeup/mk3.png",
  },
  {
    id: 5,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "180000MMK",
    image: "./images/Makeup/mk6.png",
  },
  {
    id: 6,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "380000MMK",
    image: "./images/Makeup/mk8.png",
  },
  {
    id: 7,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "560000MMK",
    image: "./images/Makeup/mk10.png",
  },
  {
    id: 8,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "780000MMK",
    image: "./images/Makeup/mk8.png",
  },
  {
    id: 9,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/Makeup/mk11.png",
  },
  {
    id: 10,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/Makeup/mk12.png",
  },
  {
    id: 11,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "50000MMK",
    image: "./images/Makeup/mk17.png",
  },
  {
    id: 12,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "380000MMK",
    image: "./images/Makeup/mk8.png",
  },
  {
    id: 13,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "560000MMK",
    image: "./images/Makeup/mk10.png",
  },
  {
    id: 14,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "780000MMK",
    image: "./images/Makeup/mk8.png",
  },
  {
    id: 15,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/Makeup/mk11.png",
  },
  {
    id: 16,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/Makeup/mk12.png",
  },
];

export const makeup_eyeshadow = [
  {
    id: 1,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/skin-care/S21.png",
  },
  {
    id: 2,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "140000MMK",
    image: "./images/Makeup/mk13.png",
  },
  {
    id: 3,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "30000MMK",
    image: "./images/Makeup/mk10.png",
  },
  {
    id: 4,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "40000MMK",
    image: "./images/Makeup/mk1.png",
  },
  {
    id: 5,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "180000MMK",
    image: "./images/Makeup/mk12.png",
  },
  {
    id: 6,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "380000MMK",
    image: "./images/Makeup/mk14.png",
  },
  {
    id: 7,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "560000MMK",
    image: "./images/Makeup/mk13.png",
  },
  {
    id: 8,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "780000MMK",
    image: "./images/Makeup/mk2.png",
  },
  {
    id: 9,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/Makeup/mk8.png",
  },
  {
    id: 10,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/Makeup/n2.png",
  },
  {
    id: 11,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "50000MMK",
    image: "./images/Makeup/mk4.png",
  },
  {
    id: 12,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "380000MMK",
    image: "./images/Makeup/mk3.png",
  },
  {
    id: 13,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "560000MMK",
    image: "./images/Makeup/mk10.png",
  },
  {
    id: 14,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "780000MMK",
    image: "./images/Makeup/mk8.png",
  },
  {
    id: 15,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/Makeup/mk11.png",
  },
  {
    id: 16,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/Makeup/mk12.png",
  },
];

export const makeup_twoway = [
  {
    id: 1,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/skin-care/S21.png",
  },
  {
    id: 2,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "140000MMK",
    image: "./images/Makeup/mk13.png",
  },
  {
    id: 3,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "30000MMK",
    image: "./images/Makeup/mk10.png",
  },
  {
    id: 4,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "40000MMK",
    image: "./images/Makeup/mk1.png",
  },
  {
    id: 5,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "180000MMK",
    image: "./images/Makeup/mk12.png",
  },
  {
    id: 6,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "380000MMK",
    image: "./images/Makeup/mk14.png",
  },
  {
    id: 7,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "560000MMK",
    image: "./images/Makeup/mk13.png",
  },
  {
    id: 8,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "780000MMK",
    image: "./images/Makeup/mk2.png",
  },
  {
    id: 9,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/Makeup/mk8.png",
  },
  {
    id: 10,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/Makeup/n2.png",
  },
  {
    id: 11,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "50000MMK",
    image: "./images/Makeup/mk4.png",
  },
  {
    id: 12,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "380000MMK",
    image: "./images/Makeup/mk3.png",
  },
  {
    id: 13,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "560000MMK",
    image: "./images/Makeup/mk10.png",
  },
  {
    id: 14,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "780000MMK",
    image: "./images/Makeup/mk8.png",
  },
  {
    id: 15,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/Makeup/mk11.png",
  },
  {
    id: 16,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/Makeup/mk12.png",
  },
];

export const lipstick_foundation = [
  {
    id: 1,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/lipstick/L17.png",
  },
  {
    id: 2,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "140000MMK",
    image: "./images/lipstick/L16.png",
  },
  {
    id: 3,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "30000MMK",
    image: "./images/lipstick/L10.png",
  },
  {
    id: 4,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "40000MMK",
    image: "./images/lipstick/n2.png",
  },
  {
    id: 5,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "180000MMK",
    image: "./images/skin-care/S5.png",
  },
  {
    id: 6,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "380000MMK",
    image: "./images/skin-care/S6.png",
  },
  {
    id: 7,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "560000MMK",
    image: "./images/skin-care/S7.png",
  },
  {
    id: 8,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "780000MMK",
    image: "./images/Makeup/mk2.png",
  },
  {
    id: 9,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/Makeup/mk8.png",
  },
  {
    id: 10,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/Makeup/n2.png",
  },
  {
    id: 11,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "50000MMK",
    image: "./images/Makeup/mk8.png",
  },
  {
    id: 12,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "380000MMK",
    image: "./images/Makeup/mk3.png",
  },
  {
    id: 13,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "560000MMK",
    image: "./images/Makeup/mk10.png",
  },
  {
    id: 14,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "780000MMK",
    image: "./images/Makeup/mk3.png",
  },
  {
    id: 15,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/Makeup/mk11.png",
  },
  {
    id: 16,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/Makeup/mk12.png",
  },
];

export const lipstick_chanel = [
  {
    id: 1,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/lipstick/L17.png",
  },
  {
    id: 2,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "140000MMK",
    image: "./images/lipstick/L16.png",
  },
  {
    id: 3,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "30000MMK",
    image: "./images/lipstick/L10.png",
  },
  {
    id: 4,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "40000MMK",
    image: "./images/lipstick/n2.png",
  },
  {
    id: 5,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "180000MMK",
    image: "./images/skin-care/S5.png",
  },
  {
    id: 6,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "380000MMK",
    image: "./images/skin-care/S6.png",
  },
  {
    id: 7,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "560000MMK",
    image: "./images/skin-care/S7.png",
  },
  {
    id: 8,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "780000MMK",
    image: "./images/Makeup/mk2.png",
  },
  {
    id: 9,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/Makeup/mk8.png",
  },
  {
    id: 10,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/Makeup/n2.png",
  },
  {
    id: 11,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "50000MMK",
    image: "./images/Makeup/mk4.png",
  },
  {
    id: 12,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "380000MMK",
    image: "./images/Makeup/mk3.png",
  },
  {
    id: 13,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "560000MMK",
    image: "./images/Makeup/mk10.png",
  },
  {
    id: 14,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "780000MMK",
    image: "./images/Makeup/mk8.png",
  },
  {
    id: 15,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/Makeup/mk11.png",
  },
  {
    id: 16,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/Makeup/mk12.png",
  },
];

export const lipstick_loreal = [
  {
    id: 1,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/lipstick/L17.png",
  },
  {
    id: 2,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "140000MMK",
    image: "./images/lipstick/L16.png",
  },
  {
    id: 3,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "30000MMK",
    image: "./images/lipstick/L10.png",
  },
  {
    id: 4,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "40000MMK",
    image: "./images/lipstick/n2.png",
  },
  {
    id: 5,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "180000MMK",
    image: "./images/skin-care/S5.png",
  },
  {
    id: 6,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "380000MMK",
    image: "./images/skin-care/S6.png",
  },
  {
    id: 7,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "560000MMK",
    image: "./images/skin-care/S7.png",
  },
  {
    id: 8,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "780000MMK",
    image: "./images/Makeup/mk2.png",
  },
  {
    id: 9,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/Makeup/mk8.png",
  },
  {
    id: 10,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/Makeup/n2.png",
  },
  {
    id: 11,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "50000MMK",
    image: "./images/Makeup/mk4.png",
  },
  {
    id: 12,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "380000MMK",
    image: "./images/Makeup/mk3.png",
  },
  {
    id: 13,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "560000MMK",
    image: "./images/Makeup/mk10.png",
  },
  {
    id: 14,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "780000MMK",
    image: "./images/Makeup/mk8.png",
  },
  {
    id: 15,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/Makeup/mk11.png",
  },
  {
    id: 16,
    title: "3CE",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/Makeup/mk12.png",
  },
];

export const hair_themixbysu = [
  {
    id: 1,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/shampoo/S11.png",
  },
  {
    id: 2,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "180000MMK",
    image: "./images/shampoo/S13.png",
  },
  {
    id: 3,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "240000MMK",
    image: "./images/shampoo/S15.png",
  },
  {
    id: 4,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "330000MMK",
    image: "./images/shampoo/S17.png",
  },
  {
    id: 5,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "190000MMK",
    image: "./images/shampoo/S13.png",
  },
  {
    id: 6,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/shampoo/S11.png",
  },
  {
    id: 7,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/shampoo/S12.png",
  },
  {
    id: 8,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/skin-care/S8.png",
  },
  {
    id: 9,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/skin-care/S9.png",
  },
  {
    id: 10,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "170000MMK",
    image: "./images/skin-care/S10.png",
  },
  {
    id: 11,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "430000MMK",
    image: "./images/skin-care/S11.png",
  },
  {
    id: 12,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "53000MMK",
    image: "./images/skin-care/S12.png",
  },
  {
    id: 13,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "230000MMK",
    image: "./images/skin-care/S13.png",
  },
  {
    id: 14,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "120000MMK",
    image: "./images/skin-care/S14.png",
  },
  {
    id: 15,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "110000MMK",
    image: "./images/skin-care/S14.png",
  },
  {
    id: 16,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "70000MMK",
    image: "./images/skin-care/S16.png",
  },
];

export const hair_bodylotion = [
  {
    id: 1,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/shampoo/S11.png",
  },
  {
    id: 2,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "180000MMK",
    image: "./images/shampoo/S13.png",
  },
  {
    id: 3,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "240000MMK",
    image: "./images/shampoo/S15.png",
  },
  {
    id: 4,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "330000MMK",
    image: "./images/shampoo/S17.png",
  },
  {
    id: 5,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "190000MMK",
    image: "./images/shampoo/S13.png",
  },
  {
    id: 6,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/shampoo/S11.png",
  },
  {
    id: 7,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/shampoo/S12.png",
  },
  {
    id: 8,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/skin-care/S8.png",
  },
  {
    id: 9,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/skin-care/S9.png",
  },
  {
    id: 10,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "170000MMK",
    image: "./images/skin-care/S10.png",
  },
  {
    id: 11,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "430000MMK",
    image: "./images/skin-care/S11.png",
  },
  {
    id: 12,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "53000MMK",
    image: "./images/skin-care/S12.png",
  },
  {
    id: 13,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "230000MMK",
    image: "./images/skin-care/S13.png",
  },
  {
    id: 14,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "120000MMK",
    image: "./images/skin-care/S14.png",
  },
  {
    id: 15,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "110000MMK",
    image: "./images/skin-care/S14.png",
  },
  {
    id: 16,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "70000MMK",
    image: "./images/skin-care/S16.png",
  },
];

export const hair_showergel = [
  {
    id: 1,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/s1.png",
  },
  {
    id: 2,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "180000MMK",
    image: "./images/shampoo/S2.png",
  },
  {
    id: 3,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "240000MMK",
    image: "./images/shampoo/S3.png",
  },
  {
    id: 4,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "330000MMK",
    image: "./images/shampoo/S4.png",
  },
  {
    id: 5,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "190000MMK",
    image: "./images/shampoo/S1.png",
  },
  {
    id: 6,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/shampoo/S5.png",
  },
  {
    id: 7,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/shampoo/S5.png",
  },
  {
    id: 8,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/shampoo/S6.png",
  },
  {
    id: 9,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "130000MMK",
    image: "./images/shampoo/S7.png",
  },
  {
    id: 10,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "170000MMK",
    image: "./images/Makeup/n2.png",
  },
  {
    id: 11,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "430000MMK",
    image: "./images/skin-care/S11.png",
  },
  {
    id: 12,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "53000MMK",
    image: "./images/skin-care/S12.png",
  },
  {
    id: 13,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "230000MMK",
    image: "./images/skin-care/S13.png",
  },
  {
    id: 14,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "120000MMK",
    image: "./images/skin-care/S14.png",
  },
  {
    id: 15,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "110000MMK",
    image: "./images/skin-care/S14.png",
  },
  {
    id: 16,
    title: "Maybelline",
    name: "Fraijour Original Herb Wormwood Calming Toner",
    price: "70000MMK",
    image: "./images/skin-care/S16.png",
  },
];
